### PR TITLE
Added .gitlab-ci.yml file for Phase 5

### PR DESCRIPTION
**Pull request by benjunker**

### CODE REVIEW

**Comment by purelogiq** [comment]
Let me update this later before merging, I'll try to look at it tonight. Sorry for the delay!

**Comment by profh** [comment]
Ben,

I also purged the controller tests from this phase.  Are they being called in the ci file?

**Comment by benjunker** [comment]
Yeah, it looked like there were still some controller tests (home, item_prices, items, and purchases) in the starter code, so I included running them in the ci file.

I can take calling the controller tests out of the ci file, though, if that's better?

**Comment by profh** [comment]
Yes let’s do that since I removed the controller tests.

Qapla’

Prof. H

----------------------------------
Professor Larry Heimann
Information Systems Program
Carnegie Mellon University
profh@cmu.edu

"In theory, theory and practice are the same.
 In practice, they're not."

**Comment by purelogiq** [comment]
Hey, it looks like were not doing controller or cucumber test this semester? (If so yes! I think that's a great change to let people get creative).

This yml file looks fine, although we are missing the test_helper.rb change that lets us see the coverage output in the console. I sort of have my hands tied right now so I actually can't update this, but @benjunker or @profh  if you want to just look at this change here [https://github.com/profh/ChessStore_Phase_4_Starter/pull/1/files#diff-f14ca9959ff06f3ca2ee6b9564866954R3](https://github.com/profh/ChessStore_Phase_4_Starter/pull/1/files#diff-f14ca9959ff06f3ca2ee6b9564866954R3) then that's basically it.

I imagine we will have to make a post on piazza as we did with phase 2 to actually get people to get this change.

**Pull request merged**
